python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance Chi2  --source Art --target Clipart --seed 0 | tee PDA-OfficeHome_A2C_Chi2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance Chi2  --source Art --target Product --seed 0 | tee PDA-OfficeHome_A2P_Chi2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance Chi2  --source Art --target Real --seed 0 | tee PDA-OfficeHome_A2R_Chi2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance Chi2  --source Clipart --target Art --seed 0 | tee PDA-OfficeHome_C2A_Chi2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance Chi2  --source Clipart --target Product --seed 0 | tee PDA-OfficeHome_C2P_Chi2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance Chi2  --source Clipart --target Real --seed 0 | tee PDA-OfficeHome_C2R_Chi2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance Chi2  --source Product --target Art  --seed 0 | tee PDA-OfficeHome_P2A_Chi2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance Chi2  --source Product --target Clipart  --seed 0 | tee PDA-OfficeHome_P2C_Chi2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance Chi2  --source Product --target Real  --seed 0 | tee PDA-OfficeHome_P2R_Chi2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance Chi2  --source Real --target Art  --seed 0 | tee PDA-OfficeHome_R2A_Chi2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance Chi2  --source Real --target Clipart  --seed 0 | tee PDA-OfficeHome_R2C_Chi2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance Chi2  --source Real --target Product  --seed 0 | tee PDA-OfficeHome_R2P_Chi2_seed0.log

python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance L2  --source Art --target Clipart --seed 0 | tee PDA-OfficeHome_A2C_L2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance L2  --source Art --target Product --seed 0 | tee PDA-OfficeHome_A2P_L2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance L2  --source Art --target Real --seed 0 | tee PDA-OfficeHome_A2R_L2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance L2  --source Clipart --target Art --seed 0 | tee PDA-OfficeHome_C2A_L2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance L2  --source Clipart --target Product --seed 0 | tee PDA-OfficeHome_C2P_L2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance L2  --source Clipart --target Real --seed 0 | tee PDA-OfficeHome_C2R_L2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance L2  --source Product --target Art  --seed 0 | tee PDA-OfficeHome_P2A_L2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance L2  --source Product --target Clipart  --seed 0 | tee PDA-OfficeHome_P2C_L2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance L2  --source Product --target Real  --seed 0 | tee PDA-OfficeHome_P2R_L2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance L2  --source Real --target Art  --seed 0 | tee PDA-OfficeHome_R2A_L2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance L2  --source Real --target Clipart  --seed 0 | tee PDA-OfficeHome_R2C_L2_seed0.log
python demo.py  --gpu 0   --root_dir ./data/OfficeHome --dataset OfficeHome --distance L2  --source Real --target Product  --seed 0 | tee PDA-OfficeHome_R2P_L2_seed0.log